# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160420_1452'),
        ('attendance', '0003_auto_20160425_2034'),
    ]

    operations = [
    ]
