# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_geodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='device_id',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geodata',
            name='user_id',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
