# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_geodata_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavjiRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='0000000', editable=False, max_length=200)),
                ('contact', models.IntegerField(blank=True)),
                ('item1', models.CharField(blank=True, default='0000000', editable=False, max_length=200)),
                ('item2', models.CharField(blank=True, default='0000000', editable=False, max_length=200)),
                ('cost', models.FloatField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
