# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.TextField(default=datetime.datetime(2016, 11, 23, 11, 25, 46, 742251)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(default=datetime.datetime(2016, 11, 23, 11, 27, 7, 582983), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_content',
            field=models.TextField(default=datetime.datetime(2016, 11, 23, 11, 27, 37, 959095)),
            preserve_default=False,
        ),
    ]
