# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20161123_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('publish_date',)},
        ),
    ]
